--
-- Agent H Stage 1: tenant foundation
-- Every tenant-scoped table gets tenant_id + org_type. org_type is kept in
-- sync with tenants.org_type via a trigger (set_tenant_context_default) so
-- it can never drift out of sync with the tenant it belongs to.
--

create table public.tenants (
    id bigint generated by default as identity primary key,
    name text not null,
    org_type text not null check (org_type in ('staffing', 'in_house')),
    created_at timestamp with time zone not null default now()
);

comment on table public.tenants is 'A recruiting organization using Agent H: either a staffing firm (e.g. TalentCursor) or an in-house recruiting team at a company. org_type drives which mode of the product a tenant sees.';

-- Seed tenant: staffing mode (TalentCursor) is built first per Stage 1 resolution.
insert into public.tenants (name, org_type) values ('TalentCursor', 'staffing');

-- Resolves the tenant of the currently authenticated user, via their sales row.
create or replace function public.current_tenant_id() returns bigint
    language plpgsql security definer
    set search_path to ''
    as $$
begin
  return (select tenant_id from public.sales where user_id = auth.uid());
end;
$$;

comment on function public.current_tenant_id() is 'Returns the tenant_id of the logged-in recruiter. Used throughout RLS policies for tenant isolation.';

-- Generic before-insert trigger: auto-fills tenant_id from the inserting
-- user's own sales row (mirrors the existing set_sales_id_default pattern),
-- then copies org_type from the resolved tenant so the two can never disagree.
-- Not attached to public.sales itself -- that table's tenant assignment
-- happens at signup time, inside handle_new_user().
create or replace function public.set_tenant_context_default() returns trigger
    language plpgsql security definer
    set search_path to ''
    as $$
declare
  resolved_tenant_id bigint;
begin
  if new.tenant_id is null then
    select tenant_id into resolved_tenant_id from public.sales where user_id = auth.uid();
    new.tenant_id := resolved_tenant_id;
  end if;

  if new.tenant_id is not null then
    select org_type into new.org_type from public.tenants where id = new.tenant_id;
  end if;

  return new;
end;
$$;

comment on function public.set_tenant_context_default() is 'Auto-populates tenant_id (from the current user) and org_type (copied from that tenant) on insert, for every tenant-scoped table.';

-- Add tenant_id + org_type to every existing Atomic CRM table that holds
-- tenant data. Excluded deliberately: favicons_excluded_domains (shared
-- reference data, not tenant data) and configuration (restructured to a
-- per-tenant table in a later schema file in this same stage).
alter table public.sales add column tenant_id bigint references public.tenants(id);
alter table public.sales add column org_type text;

alter table public.companies add column tenant_id bigint references public.tenants(id);
alter table public.companies add column org_type text;

alter table public.contacts add column tenant_id bigint references public.tenants(id);
alter table public.contacts add column org_type text;

alter table public.contact_notes add column tenant_id bigint references public.tenants(id);
alter table public.contact_notes add column org_type text;

alter table public.deals add column tenant_id bigint references public.tenants(id);
alter table public.deals add column org_type text;

alter table public.deal_notes add column tenant_id bigint references public.tenants(id);
alter table public.deal_notes add column org_type text;

alter table public.tags add column tenant_id bigint references public.tenants(id);
alter table public.tags add column org_type text;

alter table public.tasks add column tenant_id bigint references public.tenants(id);
alter table public.tasks add column org_type text;

-- Attach the auto-fill trigger to every table above except sales (handled
-- specially at signup).
create or replace trigger set_company_tenant_context_trigger
    before insert on public.companies
    for each row execute function public.set_tenant_context_default();

create or replace trigger set_contact_tenant_context_trigger
    before insert on public.contacts
    for each row execute function public.set_tenant_context_default();

create or replace trigger set_contact_notes_tenant_context_trigger
    before insert on public.contact_notes
    for each row execute function public.set_tenant_context_default();

create or replace trigger set_deal_tenant_context_trigger
    before insert on public.deals
    for each row execute function public.set_tenant_context_default();

create or replace trigger set_deal_notes_tenant_context_trigger
    before insert on public.deal_notes
    for each row execute function public.set_tenant_context_default();

create or replace trigger set_tags_tenant_context_trigger
    before insert on public.tags
    for each row execute function public.set_tenant_context_default();

create or replace trigger set_tasks_tenant_context_trigger
    before insert on public.tasks
    for each row execute function public.set_tenant_context_default();

-- Update the auth-signup trigger function to resolve and stamp tenant_id/org_type
-- onto the new sales row (bootstraps to the first tenant if none specified --
-- fine while there's only one tenant; a real invite/tenant-picker flow is
-- later-stage product work, not schema).
CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  sales_count int;
  target_tenant_id bigint;
  target_org_type text;
begin
  select count(id) into sales_count
  from public.sales;

  target_tenant_id := nullif(new.raw_user_meta_data ->> 'tenant_id', '')::bigint;

  if target_tenant_id is null then
    select id into target_tenant_id from public.tenants order by id limit 1;
  end if;

  select org_type into target_org_type from public.tenants where id = target_tenant_id;

  insert into public.sales (first_name, last_name, email, user_id, administrator, tenant_id, org_type)
  values (
    coalesce(new.raw_user_meta_data ->> 'first_name', new.raw_user_meta_data -> 'custom_claims' ->> 'first_name', 'Pending'),
    coalesce(new.raw_user_meta_data ->> 'last_name', new.raw_user_meta_data -> 'custom_claims' ->> 'last_name', 'Pending'),
    new.email,
    new.id,
    case when sales_count > 0 then FALSE else TRUE end,
    target_tenant_id,
    target_org_type
  );
  return new;
end;
$$;
