--
-- Agent H Stage 1: candidates entity + relationship_type on companies
--

-- Generic updated_at helper (candidates is the first table in Agent H that
-- needs one; reused wherever else it's needed later).
create or replace function public.set_updated_at() returns trigger
    language plpgsql
    set search_path to ''
    as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.candidates (
    id bigint generated by default as identity primary key,
    tenant_id bigint references public.tenants(id),
    org_type text,
    first_name text,
    last_name text,
    email_jsonb jsonb,
    phone_jsonb jsonb,
    current_title text,
    current_company_id bigint references public.companies(id),
    linkedin_url text,
    source text,
    status text,
    created_by_sales_id bigint references public.sales(id),
    -- Collision-avoidance hook: lets one recruiter's active outreach be
    -- visible to a teammate before they independently contact the same
    -- person. Just the field for now -- the real-time notification/UI
    -- layer is a feature for the scheduling/screening stage, not schema.
    engaged_by_sales_id bigint references public.sales(id),
    engaged_since timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

comment on table public.candidates is 'Job seekers. Deliberately separate from public.contacts, which represents organizational people (hiring managers, staffing-client contacts, past-employer contacts) -- keeps recruiting-specific fields off the generic CRM contact record.';
comment on column public.candidates.engaged_by_sales_id is 'Collision-avoidance: which recruiter is actively engaging this candidate right now, if any. Separate from assignment (see candidate_assignments) -- this is about not double-contacting someone, not about who owns the work.';

create index candidates_company_id_idx on public.candidates using btree (current_company_id);
create index candidates_tenant_id_idx on public.candidates using btree (tenant_id);

create or replace trigger set_candidates_tenant_context_trigger
    before insert on public.candidates
    for each row execute function public.set_tenant_context_default();

-- set_sales_id_default() writes to NEW.sales_id, but candidates uses
-- created_by_sales_id -- reuse the same auto-attribution idea with its own
-- small trigger instead of forcing a column rename.
create or replace function public.set_candidate_created_by_default() returns trigger
    language plpgsql
    set search_path to 'public'
    as $$
begin
  if new.created_by_sales_id is null then
    select id into new.created_by_sales_id from sales where user_id = auth.uid();
  end if;
  return new;
end;
$$;

create or replace trigger set_candidates_created_by_trigger
    before insert on public.candidates
    for each row execute function public.set_candidate_created_by_default();

create or replace trigger set_candidates_updated_at_trigger
    before update on public.candidates
    for each row execute function public.set_updated_at();

-- Relationship-type field on companies: distinguishes why this
-- organization is in the system at all -- a candidate's past employer, a
-- staffing client TalentCursor is filling roles for, or (in-house mode,
-- later) the org's own company record.
alter table public.companies add column relationship_type text
    check (relationship_type in ('past_employer', 'staffing_client', 'own_org'));

comment on column public.companies.relationship_type is 'Why this company exists in the graph: past_employer (a candidate worked there), staffing_client (TalentCursor is filling roles for them), or own_org (in-house mode only -- the tenant''s own company record).';
