--
-- Agent H Stage 1: role-brief fields on deals, and dedicated assignment
-- tables (separate from ownership/creation, per PRD Section 3: a
-- hard-to-fill role can have two or three recruiters assigned to source it
-- in parallel, all able to see and act on it).
--

-- deals is kept as the physical table name (not renamed to role_briefs) so
-- Stage 1 stays schema-only -- a rename would ripple into Atomic's existing
-- views (activity_log, companies_summary) and frontend resource wiring,
-- which is Stage 2+ territory once the role-brief UI is actually built.
alter table public.deals add column jd_text text;
alter table public.deals add column seniority text;
alter table public.deals add column location text;
alter table public.deals add column role_status text;
-- Reserved cross-tenant sharing hook (Section 3): nullable, not enforced by
-- RLS yet. Shape is set for the realistic near-term case -- a TalentCursor
-- role shared with one client in-house tenant -- not built until that stage
-- arrives.
alter table public.deals add column shared_with_tenant_id bigint references public.tenants(id);

comment on column public.deals.jd_text is 'Role brief: structured/natural-language job description text (Agent H field; deals.stage/category/amount are the original Atomic CRM sales-pipeline fields, left dormant here).';
comment on column public.deals.shared_with_tenant_id is 'Reserved, not enforced: the cross-tenant hook for a TalentCursor role shared with a client''s in-house tenant. RLS does not yet grant visibility based on this column -- wiring that in is deferred until the cross-tenant collaboration stage actually arrives.';

create table public.candidate_assignments (
    id bigint generated by default as identity primary key,
    tenant_id bigint references public.tenants(id),
    org_type text,
    candidate_id bigint not null references public.candidates(id) on delete cascade,
    sales_id bigint not null references public.sales(id),
    assigned_at timestamp with time zone not null default now(),
    unique (candidate_id, sales_id)
);

create table public.role_brief_assignments (
    id bigint generated by default as identity primary key,
    tenant_id bigint references public.tenants(id),
    org_type text,
    deal_id bigint not null references public.deals(id) on delete cascade,
    sales_id bigint not null references public.sales(id),
    assigned_at timestamp with time zone not null default now(),
    unique (deal_id, sales_id)
);

comment on table public.candidate_assignments is 'Who is assigned to work a candidate -- separate from created_by_sales_id (who created the record). Many-to-many: several recruiters can be assigned to the same candidate.';
comment on table public.role_brief_assignments is 'Who is assigned to source/work a role brief (deals row) -- separate from sales_id (who created it). Many-to-many, e.g. 2-3 recruiters parallel-sourcing a hard-to-fill role.';

create index candidate_assignments_candidate_id_idx on public.candidate_assignments using btree (candidate_id);
create index candidate_assignments_sales_id_idx on public.candidate_assignments using btree (sales_id);
create index role_brief_assignments_deal_id_idx on public.role_brief_assignments using btree (deal_id);
create index role_brief_assignments_sales_id_idx on public.role_brief_assignments using btree (sales_id);

create or replace trigger set_candidate_assignments_tenant_context_trigger
    before insert on public.candidate_assignments
    for each row execute function public.set_tenant_context_default();

create or replace trigger set_role_brief_assignments_tenant_context_trigger
    before insert on public.role_brief_assignments
    for each row execute function public.set_tenant_context_default();
