--
-- Agent H Stage 1: append-only event log. Every action, on every entity,
-- immutable. Underused at first (no update/delete path is even wired to
-- write to it yet -- that happens as each stage builds real actions), but
-- the table and its immutability guarantee exist now because retrofitting
-- "no one can quietly edit history" after the fact is exactly the kind of
-- thing that's cheap today and painful later.
--

create table public.events (
    id bigint generated by default as identity primary key,
    tenant_id bigint references public.tenants(id),
    org_type text,
    actor_sales_id bigint references public.sales(id),
    entity_type text not null,
    entity_id bigint not null,
    action text not null,
    payload jsonb not null default '{}'::jsonb,
    created_at timestamp with time zone not null default now()
);

comment on table public.events is 'Append-only audit/event log. actor_sales_id is a real recruiter, not a tenant-level placeholder. No update or delete is permitted (see RLS + grants) -- this table doubles as the audit trail for SOC2-readiness per PRD Section 6.';

create index events_tenant_id_idx on public.events using btree (tenant_id);
create index events_entity_idx on public.events using btree (entity_type, entity_id);
create index events_created_at_idx on public.events using btree (created_at);

create or replace trigger set_events_tenant_context_trigger
    before insert on public.events
    for each row execute function public.set_tenant_context_default();

create or replace function public.set_event_actor_default() returns trigger
    language plpgsql
    set search_path to 'public'
    as $$
begin
  if new.actor_sales_id is null then
    select id into new.actor_sales_id from sales where user_id = auth.uid();
  end if;
  return new;
end;
$$;

create or replace trigger set_events_actor_trigger
    before insert on public.events
    for each row execute function public.set_event_actor_default();

-- Immutability: only signed-in recruiters can append (insert) and read
-- their own tenant's log. No one -- including admins -- gets UPDATE/DELETE
-- grants on this table (service_role, used by trusted backend jobs only, is
-- the one exception -- e.g. a future retention/erasure job under GDPR).
-- anon has no legitimate reason to touch the event log at all.
--
-- Explicit revokes below are required because Atomic CRM's own
-- 06_grants.sql sets "alter default privileges ... grant all on tables" for
-- anon/authenticated, which silently applies "all" (including update/
-- delete) to any table created afterward, including this one. Relying on
-- RLS alone (no update/delete policy exists) already blocks this in
-- practice, but immutability should not depend only on "nobody adds a
-- policy later" -- revoke the privilege outright too.
revoke all on public.events from anon;
revoke update, delete, truncate on public.events from authenticated;
grant select, insert on public.events to authenticated;
grant all on public.events to service_role;
grant all on sequence public.events_id_seq to authenticated;
grant all on sequence public.events_id_seq to service_role;
