--
-- Agent H Stage 3, checkpoint 3b: dedup/rediscovery + role-brief linkage for
-- sourced candidates.
--
-- Scope: checkpoint 3a returns raw PDL search hits but saves nothing.
-- Checkpoint 3b makes "Add to pipeline" mean something real:
--   1. A candidate found via PDL is recognized as the same person if we ever
--      see them again (same PDL profile, or same LinkedIn URL), so the same
--      person never gets duplicated into public.candidates just because
--      they turned up in two different searches (or two different roles).
--   2. A saved candidate is linked to the role brief they were sourced for,
--      via a new join table -- deals (role briefs) had no such link before
--      this file. Modeled as many-to-many (deal_candidates), matching the
--      existing candidate_assignments / role_brief_assignments pattern
--      already in 10_agent_h_role_briefs_and_assignments.sql, rather than a
--      single role_brief_id column on candidates -- a candidate can
--      genuinely be relevant to more than one open role over time.
--
-- Deliberately NOT in scope here (per Harsha's decision: results are saved
-- only on explicit recruiter action, not automatically for every PDL hit):
--   - no auto-save of raw search results -- see save-sourced-candidate edge
--     function, called only when a recruiter clicks "Add to pipeline"
--   - no fuzzy name/company matching yet -- PDL's own person id and a
--     LinkedIn URL are both close to unique identifiers already, so exact
--     matching on those two catches the realistic case (the same PDL
--     profile turning up again). Fuzzy matching is the last-resort tier in
--     the architecture doc's dedup design, needed once resumes/manual
--     entries (which won't have a pdl_id) are also flowing through this
--     same table -- not needed to make 3b's PDL-only scope work correctly.
--

-- PDL's own unique person identifier. Stored so a repeat PDL search (same
-- role, or a different role that happens to surface the same person) is
-- recognized as "already have this person" rather than silently creating a
-- second candidate row for them.
alter table public.candidates add column pdl_id text;

comment on column public.candidates.pdl_id is 'People Data Labs'' own unique person id (their "id" field from Person Search/Enrich responses). Null for candidates that did not come from PDL (manual entry, resume upload, etc.). Primary dedup key for PDL-sourced candidates.';

-- The candidates table (Stage 1) has no columns for location, skills, or
-- anything else PDL returns beyond title/company/linkedin/contact info --
-- it wasn't designed with a PDL payload in mind. Rather than bolt on a
-- narrow column per PDL field (location_name, skills, job_title_levels, ...),
-- store the full raw PDL person object verbatim here. Normalized columns
-- (current_title, linkedin_url, email_jsonb) stay the source of truth for
-- display/filtering/dedup; source_raw exists so nothing PDL gave us is
-- silently lost, and so 3c's semantic matching (which needs skills) and 3d's
-- enrichment have a real payload to read from without another migration.
alter table public.candidates add column source_raw jsonb;

comment on column public.candidates.source_raw is 'Full raw payload from wherever this candidate was sourced (e.g. the complete PDL person object for source=''pdl_search''). Null for candidates entered manually. Not used for display directly -- normalized columns are.';

-- Partial unique indexes (not a blanket unique constraint) because most
-- candidates -- manual entries, resume uploads -- will have pdl_id null and
-- plenty of candidates won't have a linkedin_url on file either. Scoped to
-- tenant: two different tenants independently sourcing the same real person
-- is not a collision we want to block (each tenant's pipeline is its own).
create unique index candidates_tenant_pdl_id_uidx
    on public.candidates (tenant_id, pdl_id)
    where pdl_id is not null;

create unique index candidates_tenant_linkedin_url_uidx
    on public.candidates (tenant_id, linkedin_url)
    where linkedin_url is not null;

-- Links a candidate to a role brief (deals row) they were sourced for or are
-- otherwise relevant to. Many-to-many: the same candidate can be linked to
-- more than one open role over time (e.g. sourced for role A, later also
-- surfaces as a fit for role B), and a role brief will typically have many
-- linked candidates.
create table public.deal_candidates (
    id bigint generated by default as identity primary key,
    tenant_id bigint references public.tenants(id),
    org_type text,
    deal_id bigint not null references public.deals(id) on delete cascade,
    candidate_id bigint not null references public.candidates(id) on delete cascade,
    -- How this candidate came to be linked to this role brief. 'pdl_search'
    -- for now (the only sourcing channel that exists); other values
    -- (resume_upload, manual, referral, ...) are later-channel work per the
    -- multi-channel ingestion scope, not invented here.
    sourced_via text not null default 'pdl_search',
    created_at timestamp with time zone not null default now(),
    unique (deal_id, candidate_id)
);

comment on table public.deal_candidates is 'Which candidates are linked to which role briefs (deals), and how they got linked. Separate from candidate_assignments (which recruiter is working a candidate) -- this is about which role(s) a candidate is being considered for.';

create index deal_candidates_deal_id_idx on public.deal_candidates using btree (deal_id);
create index deal_candidates_candidate_id_idx on public.deal_candidates using btree (candidate_id);
create index deal_candidates_tenant_id_idx on public.deal_candidates using btree (tenant_id);

create or replace trigger set_deal_candidates_tenant_context_trigger
    before insert on public.deal_candidates
    for each row execute function public.set_tenant_context_default();

-- RLS: same tenant-scoped read/insert/delete pattern as candidate_assignments
-- and role_brief_assignments in 13_agent_h_rls_tenant_scoping.sql. Defined
-- here (rather than back in file 13) since this table doesn't exist until
-- this file runs -- no update policy, mirroring those two tables (a link
-- either exists or doesn't; it isn't edited in place).
alter table public.deal_candidates enable row level security;

create policy "Deal candidates read within tenant" on public.deal_candidates for select to authenticated
    using (tenant_id = public.current_tenant_id());
create policy "Deal candidates insert within tenant" on public.deal_candidates for insert to authenticated
    with check (tenant_id = public.current_tenant_id());
create policy "Deal candidates delete within tenant" on public.deal_candidates for delete to authenticated
    using (tenant_id = public.current_tenant_id());
