--
-- Agent H Stage 3: calibration loop.
--
-- Why this exists: query-tightening against PDL (see the header comment in
-- source-candidates-discovery/index.ts) has a hard ceiling -- PDL's
-- controlled skill vocabulary and coarse job_title_levels taxonomy mean the
-- boolean query can only narrow so far before it risks losing real matches.
-- On top of that, a LinkedIn/PDL profile is not the source of truth -- it's
-- frequently stale -- so no amount of query engineering alone can guarantee
-- "best matches" out of a 6000+ pool.
--
-- The calibration loop is a cheap, fast gut-check that uses the recruiter's
-- own judgment instead: before committing to a full pull, show them the top
-- 3 Voyage-ranked candidates for a role brief and capture whether each one
-- is actually a fit, plus why/why not. This is recruiter signal that PDL's
-- boolean engine structurally cannot produce on its own.
--
-- v1 scope, deliberately limited (per Harsha's confirmation "Build
-- calibration loop now"):
--   - Capture fit/not-fit + a required reason per candidate, tied to the
--     role brief (deal) and the specific PDL candidate.
--   - Store a snapshot of the candidate as shown at review time (title,
--     company, location, skills, etc.) so the feedback stays meaningful even
--     if the underlying PDL record changes later.
--   - Display only. This table is NOT read by the ranking/query logic yet --
--     using this feedback to auto-reweight future searches is a real
--     algorithm-design question that should be answered once there's actual
--     feedback data to look at, not guessed at now. That's future work.
--

create table public.candidate_calibration_feedback (
    id bigint generated by default as identity primary key,
    tenant_id bigint references public.tenants(id),
    org_type text,
    deal_id bigint not null references public.deals(id) on delete cascade,
    -- PDL's person id for the candidate being judged. Not a foreign key to
    -- candidates.pdl_id -- calibration happens on the top-3 sample pulled
    -- straight from PDL search, before a recruiter has decided to
    -- "Add to pipeline" (which is what actually creates a candidates row).
    -- A calibration judgment should still be recordable even if the
    -- candidate is never saved.
    pdl_id text not null,
    fit boolean not null,
    reason text not null,
    candidate_snapshot jsonb,
    created_by uuid references auth.users(id) default auth.uid(),
    created_at timestamp with time zone not null default now(),
    unique (deal_id, pdl_id)
);

comment on table public.candidate_calibration_feedback is 'Recruiter fit/not-fit judgments on the top Voyage-ranked candidates shown for a role brief before a full pull, used as a cheap calibration gut-check. Display/review only in v1 -- not yet fed back into ranking or query logic.';
comment on column public.candidate_calibration_feedback.reason is 'Required: a fit or not-fit judgment with no reason isn''t useful signal for anyone reviewing calibration history later.';
comment on column public.candidate_calibration_feedback.candidate_snapshot is 'The candidate data as shown to the recruiter at review time (title, company, location, skills, etc.) -- kept so feedback stays interpretable even if the underlying PDL record later changes.';

create index candidate_calibration_feedback_deal_id_idx on public.candidate_calibration_feedback using btree (deal_id);
create index candidate_calibration_feedback_tenant_id_idx on public.candidate_calibration_feedback using btree (tenant_id);

create or replace trigger set_calibration_feedback_tenant_context_trigger
    before insert on public.candidate_calibration_feedback
    for each row execute function public.set_tenant_context_default();

-- RLS: same tenant-scoped read/insert pattern as deal_candidates -- a
-- calibration judgment either exists or doesn't, it isn't edited in place,
-- so no update policy (matching the deal_candidates/events convention).
alter table public.candidate_calibration_feedback enable row level security;

create policy "Calibration feedback read within tenant" on public.candidate_calibration_feedback for select to authenticated
    using (tenant_id = public.current_tenant_id());
create policy "Calibration feedback insert within tenant" on public.candidate_calibration_feedback for insert to authenticated
    with check (tenant_id = public.current_tenant_id());
