--
-- Agent H Stage 5: Scheduling.
--
-- One row per candidate+role-brief (deal) pair, same upsert convention as
-- candidate_scores / candidate_fit_assessments (Stage 4) -- not a booking
-- history table. A reschedule updates scheduled_at on the same row; the raw
-- Cal.com webhook payload is kept in raw_booking_payload for debugging, and
-- status transitions are visible via updated_at.
--
-- Booking mechanics: Agent H does not implement calendar OAuth itself.
-- Recruiters connect their own Google/Outlook/CalDAV calendar inside a
-- self-hosted Cal.com instance (open source, chosen over building direct
-- Google/Microsoft OAuth flows per this stage's kickoff decision); Agent H
-- generates a personalized booking-page URL (candidate name/email/metadata
-- pre-filled as query params) and receives Cal.com's booking webhooks to
-- know when a candidate actually books/reschedules/cancels a slot.
--
create table public.interviews (
    id bigint generated by default as identity primary key,
    tenant_id bigint references public.tenants(id),
    org_type text,
    deal_id bigint not null references public.deals(id) on delete cascade,
    candidate_id bigint not null references public.candidates(id) on delete cascade,
    -- link_sent: booking link generated/sent, candidate hasn't booked yet.
    -- booked / rescheduled / cancelled / completed / no_show: driven by
    -- Cal.com webhook events (see cal-webhook-receiver).
    status text not null default 'link_sent'
        check (status in ('link_sent', 'booked', 'rescheduled', 'cancelled', 'completed', 'no_show')),
    booking_link_url text,
    cal_event_type_slug text,
    -- Cal.com's own booking identifier -- how the webhook receiver finds the
    -- right row on reschedule/cancel events without re-deriving it.
    cal_booking_uid text unique,
    scheduled_at timestamp with time zone,
    scheduled_end_at timestamp with time zone,
    candidate_timezone text,
    -- Who the interview is with -- separate from created_by (who generated
    -- the link), same distinction candidates.engaged_by_sales_id draws
    -- elsewhere in this schema.
    recruiter_sales_id bigint references public.sales(id),
    confirmation_sent_at timestamp with time zone,
    reminder_sent_at timestamp with time zone,
    cancellation_reason text,
    raw_booking_payload jsonb,
    created_by uuid default auth.uid(),
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    unique (deal_id, candidate_id)
);

comment on table public.interviews is 'Stage 5 (Scheduling) booking state, one row per candidate+role-brief pair (upserted on rebook/reschedule, not history -- v1 scope, matching candidate_scores/candidate_fit_assessments). Booking itself happens on a self-hosted Cal.com instance (open source scheduling, chosen so Agent H does not need to build Google/Outlook OAuth flows directly) -- this table is Agent H''s own record of that booking, kept in sync via Cal.com webhooks.';

comment on column public.interviews.status is 'link_sent (default) -> booked -> completed is the happy path; rescheduled and cancelled are webhook-driven from Cal.com; no_show is set manually by a recruiter (Cal.com has no concept of this).';
comment on column public.interviews.cal_booking_uid is 'Cal.com''s booking UID. Null until the candidate actually books (status moves to link_sent -> booked). Unique so a webhook can look up "which interview row is this" directly.';
comment on column public.interviews.raw_booking_payload is 'Last Cal.com webhook payload received for this booking, kept for debugging -- not parsed back out anywhere.';

create index interviews_tenant_id_idx on public.interviews using btree (tenant_id);
create index interviews_deal_id_idx on public.interviews using btree (deal_id);
create index interviews_candidate_id_idx on public.interviews using btree (candidate_id);
create index interviews_scheduled_at_idx on public.interviews using btree (scheduled_at);

-- Reuses the same generic tenant-default + updated_at trigger function
-- Stage 4's two tables share, rather than writing a near-identical one.
create or replace trigger interviews_set_tenant_defaults
    before insert or update on public.interviews
    for each row execute function public.set_candidate_scores_tenant_defaults();

alter table public.interviews enable row level security;

create policy "interviews tenant isolation" on public.interviews for all to authenticated
    using (tenant_id = public.current_tenant_id())
    with check (tenant_id = public.current_tenant_id());

revoke all on public.interviews from anon;
grant select, insert, update, delete on public.interviews to authenticated;
grant all on public.interviews to service_role;
grant all on sequence public.interviews_id_seq to authenticated;
grant all on sequence public.interviews_id_seq to service_role;
