--
-- Agent H: server-side calibration pool cache.
--
-- Persists the pull + ranked discovery pool per role brief (deal), so a
-- browser refresh / new tab / different device does not lose the ranked
-- pool or re-burn vendor credits.
--
-- Design decisions:
--   - One row per deal (unique(deal_id)): a fresh "start sourcing" run
--     overwrites the previous pool, cursor, and negative reasons for that role.
--   - 30-day TTL: matches the practical staleness horizon for sourcing pools.
--     Pipelined candidates in deal_candidates are NOT affected by expiry.
--   - payload (jsonb): the raw de-duped vendor candidates returned at pull
--     time. Stored so rerank never needs a fresh vendor call.
--   - ranked (jsonb): output from rank-discovery-batch [{id, rank, why_fit}]
--     in rank order. Reset cursor=0 on rerank.
--   - cursor (int): next batch start index into the ranked pool.
--   - negative_reasons (text[]): recruiter "not a fit" signals accumulated
--     during this sourcing session; fed back into rerank calls.
--   - role_brief_snapshot (jsonb): the role brief at pull time, so rerank
--     can enrich it with avoid_signals without re-fetching the deal row.
--   - Talent Bench: rows from OTHER deals in the same tenant (non-expired)
--     are checked by the calibration-session edge function before burning
--     vendor credits. Matching bench candidates are seeded into the new role's
--     pool first. No extra schema needed — the existing rows serve as the bench.
--
-- RLS: tenant-scoped like discovery_source_attribution (13_agent_h_rls).
--

create table public.role_discovery_cache (
    id bigint generated by default as identity primary key,
    deal_id bigint not null references public.deals(id) on delete cascade,
    tenant_id bigint references public.tenants(id),
    payload jsonb not null default '[]'::jsonb,
    ranked jsonb not null default '[]'::jsonb,
    cursor integer not null default 0,
    negative_reasons text[] not null default '{}',
    role_brief_snapshot jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    expires_at timestamptz not null default (now() + interval '30 days'),
    unique (deal_id)
);

comment on table public.role_discovery_cache is
    'Server-side cache of the pull + ranked discovery pool per role brief. '
    'One row per deal. Expires after 30 days. Used by calibration-session edge '
    'function to serve next-batch and rerank without re-burning vendor credits. '
    'Also provides the Talent Bench: non-expired rows from other deals in the '
    'same tenant are scanned before new vendor calls.';

-- Auto-populate tenant_id on insert (same pattern as discovery_source_attribution)
create or replace function public.set_role_discovery_cache_tenant_id()
    returns trigger
    language plpgsql
    security definer
    set search_path to ''
    as $$
begin
    if new.tenant_id is null then
        select tenant_id into new.tenant_id
        from public.sales
        where user_id = auth.uid();
    end if;
    return new;
end;
$$;

create trigger set_role_discovery_cache_tenant_id_trigger
    before insert on public.role_discovery_cache
    for each row execute function public.set_role_discovery_cache_tenant_id();

-- Auto-update updated_at on every write
create or replace function public.touch_role_discovery_cache_updated_at()
    returns trigger
    language plpgsql
    security definer
    set search_path to ''
    as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create trigger touch_role_discovery_cache_updated_at_trigger
    before update on public.role_discovery_cache
    for each row execute function public.touch_role_discovery_cache_updated_at();

alter table public.role_discovery_cache enable row level security;

create policy "Role discovery cache read within tenant"
    on public.role_discovery_cache for select to authenticated
    using (tenant_id = public.current_tenant_id());

create policy "Role discovery cache insert within tenant"
    on public.role_discovery_cache for insert to authenticated
    with check (tenant_id = public.current_tenant_id());

create policy "Role discovery cache update within tenant"
    on public.role_discovery_cache for update to authenticated
    using (tenant_id = public.current_tenant_id())
    with check (tenant_id = public.current_tenant_id());

create policy "Role discovery cache delete within tenant"
    on public.role_discovery_cache for delete to authenticated
    using (tenant_id = public.current_tenant_id());

create index role_discovery_cache_deal_id_idx
    on public.role_discovery_cache using btree (deal_id);

create index role_discovery_cache_tenant_id_idx
    on public.role_discovery_cache using btree (tenant_id);

create index role_discovery_cache_expires_at_idx
    on public.role_discovery_cache using btree (expires_at);
