--
-- Agent H Stage 3, checkpoint 3b: dedup/rediscovery + role-brief linkage for
-- sourced candidates. See supabase/schemas/16_agent_h_candidate_dedup_and_sourcing.sql
-- for the full explanation of what/why.
--

alter table public.candidates add column pdl_id text;

comment on column public.candidates.pdl_id is 'People Data Labs'' own unique person id (their "id" field from Person Search/Enrich responses). Null for candidates that did not come from PDL (manual entry, resume upload, etc.). Primary dedup key for PDL-sourced candidates.';

alter table public.candidates add column source_raw jsonb;

comment on column public.candidates.source_raw is 'Full raw payload from wherever this candidate was sourced (e.g. the complete PDL person object for source=''pdl_search''). Null for candidates entered manually. Not used for display directly -- normalized columns are.';

create unique index candidates_tenant_pdl_id_uidx
    on public.candidates (tenant_id, pdl_id)
    where pdl_id is not null;

create unique index candidates_tenant_linkedin_url_uidx
    on public.candidates (tenant_id, linkedin_url)
    where linkedin_url is not null;

create table public.deal_candidates (
    id bigint generated by default as identity primary key,
    tenant_id bigint references public.tenants(id),
    org_type text,
    deal_id bigint not null references public.deals(id) on delete cascade,
    candidate_id bigint not null references public.candidates(id) on delete cascade,
    sourced_via text not null default 'pdl_search',
    created_at timestamp with time zone not null default now(),
    unique (deal_id, candidate_id)
);

comment on table public.deal_candidates is 'Which candidates are linked to which role briefs (deals), and how they got linked. Separate from candidate_assignments (which recruiter is working a candidate) -- this is about which role(s) a candidate is being considered for.';

create index deal_candidates_deal_id_idx on public.deal_candidates using btree (deal_id);
create index deal_candidates_candidate_id_idx on public.deal_candidates using btree (candidate_id);
create index deal_candidates_tenant_id_idx on public.deal_candidates using btree (tenant_id);

create or replace trigger set_deal_candidates_tenant_context_trigger
    before insert on public.deal_candidates
    for each row execute function public.set_tenant_context_default();

alter table public.deal_candidates enable row level security;

create policy "Deal candidates read within tenant" on public.deal_candidates for select to authenticated
    using (tenant_id = public.current_tenant_id());
create policy "Deal candidates insert within tenant" on public.deal_candidates for insert to authenticated
    with check (tenant_id = public.current_tenant_id());
create policy "Deal candidates delete within tenant" on public.deal_candidates for delete to authenticated
    using (tenant_id = public.current_tenant_id());
