-- Agent H Phase B: role_conversation_turns (shared per-deal transcript).
-- See docs/adr/ADR-617f-phase-b-role-conversation-turns.md

create table if not exists public.role_conversation_turns (
    id bigint generated by default as identity primary key,
    tenant_id bigint references public.tenants(id),
    deal_id bigint not null references public.deals(id) on delete cascade,
    speaker text not null check (speaker in ('recruiter', 'agent')),
    actor_sales_id bigint references public.sales(id),
    content text not null,
    in_reply_to bigint references public.role_conversation_turns(id) on delete set null,
    idempotency_key text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamp with time zone not null default now()
);

comment on table public.role_conversation_turns is 'Ordered recruiter↔agent transcript for a role (deals row). One shared thread per deal_id within a tenant; not an audit log — see public.events for mutations.';

create index if not exists role_conversation_turns_deal_id_created_at_idx
    on public.role_conversation_turns using btree (deal_id, created_at);

create unique index if not exists role_conversation_turns_idempotency_uniq
    on public.role_conversation_turns using btree (tenant_id, deal_id, idempotency_key)
    where idempotency_key is not null;

create or replace function public.set_role_conversation_turn_defaults()
    returns trigger
    language plpgsql
    set search_path to 'public'
    as $$
begin
    if new.tenant_id is null then
        select tenant_id into new.tenant_id from public.sales where user_id = auth.uid();
    end if;

    if new.speaker = 'agent' and auth.uid() is not null then
        raise exception 'Agent conversation turns must be written server-side';
    end if;

    if new.speaker = 'recruiter' and new.actor_sales_id is null then
        select id into new.actor_sales_id from public.sales where user_id = auth.uid();
    end if;

    return new;
end;
$$;

drop trigger if exists set_role_conversation_turn_defaults_trigger on public.role_conversation_turns;
create trigger set_role_conversation_turn_defaults_trigger
    before insert on public.role_conversation_turns
    for each row execute function public.set_role_conversation_turn_defaults();

revoke all on public.role_conversation_turns from anon;
revoke update, delete, truncate on public.role_conversation_turns from authenticated;
grant select, insert on public.role_conversation_turns to authenticated;
grant all on public.role_conversation_turns to service_role;
grant all on sequence public.role_conversation_turns_id_seq to authenticated;
grant all on sequence public.role_conversation_turns_id_seq to service_role;

alter table public.role_conversation_turns enable row level security;

drop policy if exists "Role conversation turns read within tenant" on public.role_conversation_turns;
create policy "Role conversation turns read within tenant"
    on public.role_conversation_turns for select to authenticated
    using (tenant_id = public.current_tenant_id());

drop policy if exists "Role conversation turns insert recruiter within tenant" on public.role_conversation_turns;
create policy "Role conversation turns insert recruiter within tenant"
    on public.role_conversation_turns for insert to authenticated
    with check (
        tenant_id = public.current_tenant_id()
        and speaker = 'recruiter'
        and deal_id in (
            select d.id from public.deals d where d.tenant_id = public.current_tenant_id()
        )
    );
