-- Agent H: ephemeral discovery vendor attribution.
-- Declarative source: supabase/schemas/31_agent_h_discovery_source_attribution.sql

create table public.discovery_source_attribution (
    id bigint generated by default as identity primary key,
    tenant_id bigint references public.tenants(id),
    deal_id bigint not null references public.deals(id) on delete cascade,
    source_id text not null,
    vendor text not null,
    created_at timestamp with time zone not null default now(),
    expires_at timestamp with time zone not null default (now() + interval '7 days'),
    unique (tenant_id, deal_id, source_id)
);

comment on table public.discovery_source_attribution is 'Ephemeral map from vendor person id (source_id) to discovery provider for a role brief search. Server-side only -- never exposed to the client.';

create index discovery_source_attribution_deal_id_idx
    on public.discovery_source_attribution using btree (deal_id);

create index discovery_source_attribution_expires_at_idx
    on public.discovery_source_attribution using btree (expires_at);

create or replace function public.set_discovery_source_attribution_tenant_id()
    returns trigger
    language plpgsql
    security definer
    set search_path to ''
    as $$
begin
    if new.tenant_id is null then
        select tenant_id into new.tenant_id from public.sales where user_id = auth.uid();
    end if;
    return new;
end;
$$;

create trigger set_discovery_source_attribution_tenant_id_trigger
    before insert on public.discovery_source_attribution
    for each row execute function public.set_discovery_source_attribution_tenant_id();

alter table public.discovery_source_attribution enable row level security;

create policy "Discovery source attribution read within tenant"
    on public.discovery_source_attribution for select to authenticated
    using (tenant_id = public.current_tenant_id());

create policy "Discovery source attribution insert within tenant"
    on public.discovery_source_attribution for insert to authenticated
    with check (tenant_id = public.current_tenant_id());

create policy "Discovery source attribution update within tenant"
    on public.discovery_source_attribution for update to authenticated
    using (tenant_id = public.current_tenant_id())
    with check (tenant_id = public.current_tenant_id());

create policy "Discovery source attribution delete within tenant"
    on public.discovery_source_attribution for delete to authenticated
    using (tenant_id = public.current_tenant_id());
