--
-- Agent H Stage 6: Offer.
--
-- One row per candidate+role-brief (deal) pair, same "current state, not
-- history" convention as candidate_scores / candidate_fit_assessments
-- (Stage 4) and interviews (Stage 5) -- re-sending an offer (e.g. revised
-- terms) updates the same row rather than creating a new one.
--
-- Send mechanics mirror task 76's outreach exactly: one templated email via
-- Resend, reply_to encodes candidate_id/deal_id (offer-<id>-deal-<id>@...,
-- a distinct prefix from task 76's candidate-<id>-deal-<id>@... so
-- resend-inbound-reply can tell an offer reply from a resume reply). A
-- candidate's reply is captured as free text (response_text) -- deliberately
-- not auto-classified into accepted/declined by a model; the recruiter reads
-- the actual reply and sets the final status themselves via "Mark
-- accepted/declined/negotiating" in the UI. This mirrors the PRD's own
-- "cadence + ammunition, not prediction" stance elsewhere and task 76's
-- precedent of capturing reply text rather than interpreting it.
--
create table public.offers (
    id bigint generated by default as identity primary key,
    tenant_id bigint references public.tenants(id),
    org_type text,
    deal_id bigint not null references public.deals(id) on delete cascade,
    candidate_id bigint not null references public.candidates(id) on delete cascade,
    -- draft: created but not yet emailed (not currently reachable from the
    -- UI -- send-offer creates+sends in one step -- but kept as a state so a
    -- future "save draft" doesn't need a schema change).
    -- sent -> responded is webhook-driven (any reply moves it here, once).
    -- accepted / declined / negotiating are always a recruiter's own manual
    -- call, made after reading response_text -- never set automatically.
    status text not null default 'draft'
        check (status in ('draft', 'sent', 'responded', 'accepted', 'declined', 'negotiating', 'expired')),
    position_title text,
    compensation_amount numeric,
    compensation_currency text default 'INR',
    compensation_frequency text default 'annual'
        check (compensation_frequency in ('annual', 'monthly')),
    start_date date,
    expiry_date date,
    benefits_summary text,
    sent_at timestamp with time zone,
    responded_at timestamp with time zone,
    response_text text,
    created_by uuid default auth.uid(),
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    unique (deal_id, candidate_id)
);

comment on table public.offers is 'Stage 6 (Offer) state, one row per candidate+role-brief pair (upserted on re-send, not history -- v1 scope, matching candidate_scores/interviews). Sent via one templated Resend email (send-offer); a reply is captured as free text via resend-inbound-reply, correlated by an offer-<id>-deal-<id>@... reply_to address, distinct from task 76''s candidate-<id>-deal-<id>@... prefix.';

comment on column public.offers.status is 'draft -> sent -> responded is automatic (sent on send-offer, responded on any captured reply). accepted/declined/negotiating/expired are always set manually by a recruiter reading response_text -- this table never guesses a candidate''s intent from their reply text.';
comment on column public.offers.response_text is 'Plain-text body of the candidate''s reply, captured by resend-inbound-reply. Not classified -- the recruiter reads this and sets status themselves.';

create index offers_tenant_id_idx on public.offers using btree (tenant_id);
create index offers_deal_id_idx on public.offers using btree (deal_id);
create index offers_candidate_id_idx on public.offers using btree (candidate_id);

-- Reuses the same generic tenant-default + updated_at trigger function
-- Stage 4/5's tables share, rather than writing a near-identical one.
create or replace trigger offers_set_tenant_defaults
    before insert or update on public.offers
    for each row execute function public.set_candidate_scores_tenant_defaults();

alter table public.offers enable row level security;

create policy "offers tenant isolation" on public.offers for all to authenticated
    using (tenant_id = public.current_tenant_id())
    with check (tenant_id = public.current_tenant_id());

revoke all on public.offers from anon;
grant select, insert, update, delete on public.offers to authenticated;
grant all on public.offers to service_role;
grant all on sequence public.offers_id_seq to authenticated;
grant all on sequence public.offers_id_seq to service_role;
