--
-- Agent H Stage 3: the real calibration loop.
--
-- Why this exists: candidate_calibration_feedback (schema 20) captures a
-- recruiter's fit/not-fit judgment + reason on a calibration candidate, but
-- was explicitly v1-scoped as "display/review only... not yet fed back into
-- ranking or query logic" (see that table's comment). Harsha's direct call
-- (2026-07-17, after comparing Agent H against noon.ai live): the missing
-- piece isn't a nicer UI, it's this loop -- a "not a fit" reason should turn
-- into a real, checkable search criterion, the recruiter should see the
-- blast radius (how many candidates it would newly exclude) before
-- committing, and every criterion born this way should stay visible,
-- reversible, and separately toggle-able later (Noon's "Control Panel"
-- pattern: live per-rule reject counts, Relax/Unlearn).
--
-- v1 scope, deliberately constrained to criterion kinds that map cleanly
-- onto existing, safe sections of the Coresignal query builder (see
-- source-candidates-discovery/index.ts's coresignalProvider.search):
--   - require_keyword / exclude_keyword: matched against inferred_skills +
--     active_experience_title, same fields the JD-derived required-skills/
--     exclusion-keywords filters already use.
--   - years_experience_min / years_experience_max: tightens (never loosens)
--     the JD-derived total_experience_duration_months range.
-- Anything a recruiter's rejection reason implies that does NOT map onto one
-- of these four kinds is surfaced to Claude as "not applicable" rather than
-- guessed into the wrong bucket -- see contextualize-calibration-feedback's
-- header comment in source-candidates-discovery/index.ts.
--
-- These criteria are scoped to ONE role brief and layered ON TOP OF that
-- role brief's own JD-derived fields -- they never replace or edit the deals
-- row itself, so relaxing/unlearning a criterion here can never lose the
-- recruiter's original JD data.
--

create table public.role_brief_learned_criteria (
    id bigint generated by default as identity primary key,
    tenant_id bigint references public.tenants(id),
    org_type text,
    deal_id bigint not null references public.deals(id) on delete cascade,
    criterion_type text not null check (
        criterion_type in (
            'require_keyword',
            'exclude_keyword',
            'years_experience_min',
            'years_experience_max'
        )
    ),
    -- {"keyword": "..."} for require_keyword/exclude_keyword,
    -- {"years": N} for years_experience_min/years_experience_max.
    value jsonb not null,
    -- Formal, human-readable sentence version of this criterion (Claude's
    -- "contextualized" output, e.g. "Must have between 4 and 8 years of
    -- experience in software or machine learning engineering."), shown in
    -- the Control Panel and in the blast-radius preview before a recruiter
    -- commits it -- never edited in place after creation, matching the
    -- calibration feedback table's own "judgment either exists or doesn't"
    -- convention.
    label text not null,
    -- Which calibration judgment (if any) produced this criterion. Nullable
    -- because a future entry point (e.g. the natural-language steering box)
    -- could plausibly create one without a calibration judgment behind it.
    source_feedback_id bigint references public.candidate_calibration_feedback(id) on delete set null,
    -- 'active': applied to every future search for this role brief.
    -- 'relaxed': recruiter turned it off (Noon's "Relax"/"Unlearn") -- kept,
    -- not deleted, so the Control Panel can show it and offer "Reapply"
    -- rather than losing the history of what was tried.
    status text not null default 'active' check (status in ('active', 'relaxed')),
    -- Cached result of the last blast-radius computation for this criterion
    -- (how many candidates it excludes out of the current active set) --
    -- refreshed on demand by the Control Panel, not kept live/real-time.
    -- Null until computed at least once.
    last_reject_count integer,
    last_reject_count_computed_at timestamp with time zone,
    created_by uuid references auth.users(id) default auth.uid(),
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

comment on table public.role_brief_learned_criteria is 'Structured search criteria born from calibration feedback (or, in future, the natural-language steering box), layered on top of a role brief''s own JD-derived fields. Active criteria are merged into every future Coresignal search for that role brief; relaxed ones are kept for history and can be reapplied. This is what makes candidate_calibration_feedback (schema 20) a real adaptive loop instead of display-only review.';
comment on column public.role_brief_learned_criteria.value is 'Structured payload: {"keyword": "..."} for require_keyword/exclude_keyword, {"years": N} for years_experience_min/years_experience_max.';
comment on column public.role_brief_learned_criteria.label is 'Formal, human-readable sentence version of this criterion, generated once by Claude at creation time and never edited in place -- shown in blast-radius preview and the Control Panel.';
comment on column public.role_brief_learned_criteria.status is 'active = applied to future searches; relaxed = turned off but kept for history/reapply (Noon-style Relax/Unlearn), never hard-deleted.';
comment on column public.role_brief_learned_criteria.last_reject_count is 'Cached count of how many candidates this criterion currently excludes, refreshed on demand -- not a live/real-time value.';

create index role_brief_learned_criteria_deal_id_idx on public.role_brief_learned_criteria using btree (deal_id);
create index role_brief_learned_criteria_tenant_id_idx on public.role_brief_learned_criteria using btree (tenant_id);
create index role_brief_learned_criteria_status_idx on public.role_brief_learned_criteria using btree (status);

create or replace trigger set_role_brief_learned_criteria_tenant_context_trigger
    before insert on public.role_brief_learned_criteria
    for each row execute function public.set_tenant_context_default();

create or replace trigger set_role_brief_learned_criteria_updated_at_trigger
    before update on public.role_brief_learned_criteria
    for each row execute function public.set_updated_at();

-- RLS: same tenant-scoped pattern as candidate_calibration_feedback, but
-- WITH an update policy this time -- unlike a calibration judgment (which
-- is immutable once made), a learned criterion's status is meant to be
-- toggled (Relax / Reapply) after creation.
alter table public.role_brief_learned_criteria enable row level security;

create policy "Learned criteria read within tenant" on public.role_brief_learned_criteria for select to authenticated
    using (tenant_id = public.current_tenant_id());
create policy "Learned criteria insert within tenant" on public.role_brief_learned_criteria for insert to authenticated
    with check (tenant_id = public.current_tenant_id());
create policy "Learned criteria status update within tenant" on public.role_brief_learned_criteria for update to authenticated
    using (tenant_id = public.current_tenant_id())
    with check (tenant_id = public.current_tenant_id());
