-- Agent H Unipile Phase 4: LinkedIn outreach sequence.
-- Adds outreach tracking columns to deal_candidates, daily-cap columns
-- to sales, and a minimal follow-up schedule table.
-- Corresponding declarative schema: supabase/schemas/34_agent_h_linkedin_outreach.sql

-- Outreach channel and message tracking on deal_candidates.
alter table public.deal_candidates
    add column if not exists outreach_channel text,
    add column if not exists outreach_message_body text,
    add column if not exists outreach_approved_at timestamp with time zone,
    add column if not exists outreach_sent_at timestamp with time zone,
    add column if not exists linkedin_provider_id text;

alter table public.deal_candidates
    add constraint deal_candidates_outreach_channel_check
    check (outreach_channel is null or outreach_channel in ('email', 'linkedin_connection', 'linkedin_inmail'));

comment on column public.deal_candidates.outreach_channel is 'Channel used for first outreach: email (Resend), linkedin_connection (connection request ≤300 chars), or linkedin_inmail (open-profile InMail). Null until outreach is sent.';
comment on column public.deal_candidates.outreach_message_body is 'The exact message body that was approved and sent (connection note or InMail body). Null for email channel.';
comment on column public.deal_candidates.outreach_approved_at is 'When the recruiter approved the prepared outreach draft (Phase C approval timestamp).';
comment on column public.deal_candidates.outreach_sent_at is 'When the outreach was actually dispatched (Unipile or Resend call succeeded).';
comment on column public.deal_candidates.linkedin_provider_id is 'Unipile provider_id for the candidate LinkedIn profile — resolved at prepare time from linkedin_url.';

-- Daily LinkedIn send cap tracking on the sales (recruiter) row.
alter table public.sales
    add column if not exists linkedin_daily_send_cap integer not null default 80,
    add column if not exists linkedin_sends_today integer not null default 0,
    add column if not exists linkedin_sends_reset_date date;

comment on column public.sales.linkedin_daily_send_cap is 'Maximum LinkedIn outreach sends per calendar day for this recruiter seat. Default 80.';
comment on column public.sales.linkedin_sends_today is 'Number of LinkedIn sends already dispatched today. Reset to 0 when date crosses linkedin_sends_reset_date.';
comment on column public.sales.linkedin_sends_reset_date is 'The calendar date linkedin_sends_today was last reset to 0.';

-- Minimal follow-up schedule table (Phase 4 stub; cron execution deferred).
create table if not exists public.linkedin_outreach_follow_ups (
    id bigint generated by default as identity primary key,
    tenant_id bigint references public.tenants(id),
    deal_candidate_id bigint not null references public.deal_candidates(id) on delete cascade,
    scheduled_for timestamp with time zone not null,
    follow_up_type text not null default 'connection_reminder',
    status text not null default 'pending',
    created_at timestamp with time zone not null default now(),
    constraint linkedin_follow_ups_type_check
        check (follow_up_type in ('connection_reminder', 'inmail_follow_up')),
    constraint linkedin_follow_ups_status_check
        check (status in ('pending', 'sent', 'cancelled', 'skipped'))
);

comment on table public.linkedin_outreach_follow_ups is 'Scheduled LinkedIn follow-up messages queued after a first outreach send. Phase 4 stub — cron execution is deferred (see ADR).';

create index if not exists linkedin_follow_ups_deal_candidate_idx
    on public.linkedin_outreach_follow_ups using btree (deal_candidate_id);
create index if not exists linkedin_follow_ups_scheduled_for_idx
    on public.linkedin_outreach_follow_ups using btree (scheduled_for)
    where status = 'pending';
create index if not exists linkedin_follow_ups_tenant_idx
    on public.linkedin_outreach_follow_ups using btree (tenant_id);

create or replace trigger set_linkedin_follow_ups_tenant_context_trigger
    before insert on public.linkedin_outreach_follow_ups
    for each row execute function public.set_tenant_context_default();

alter table public.linkedin_outreach_follow_ups enable row level security;

create policy "LinkedIn follow-ups read within tenant"
    on public.linkedin_outreach_follow_ups for select to authenticated
    using (tenant_id = public.current_tenant_id());

create policy "LinkedIn follow-ups insert within tenant"
    on public.linkedin_outreach_follow_ups for insert to authenticated
    with check (tenant_id = public.current_tenant_id());
