-- Bugfix: Stage 1 made tenant_id the primary key of public.configuration
-- and dropped its original `id` column entirely. That broke Atomic's
-- existing frontend code, which (like the rest of react-admin/ra-core)
-- assumes every resource has a plain `id` column to reference records by.
-- Fix: restore `id` as a normal identity primary key, and make tenant_id a
-- unique scoping column instead of the primary key itself. Still fully
-- achieves "one config row per tenant" -- just via a unique constraint
-- instead of repurposing tenant_id as the actual primary key.
--
-- Already applied directly to the live Supabase project
-- (fbkdypullttetardrgdu / "Agent H") as migration
-- agent_h_configuration_restore_id_pk. See
-- supabase/schemas/12_agent_h_configuration_per_tenant.sql for the
-- corrected declarative source-of-truth version.

alter table public.configuration drop constraint configuration_pkey;
alter table public.configuration add column id bigint generated by default as identity;
alter table public.configuration add constraint configuration_pkey primary key (id);
alter table public.configuration add constraint configuration_tenant_id_key unique (tenant_id);
